sudo: false

addons:
  apt:
    packages:
      - libgmp-dev

env:
  - STACK_YAML=stack-servant-0.4.yaml
  - STACK_YAML=stack-servant-0.5.yaml
  - STACK_YAML=stack-servant-0.6.yaml
  - STACK_YAML=stack-servant-0.7.yaml
  - STACK_YAML=stack.yaml

install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version

script:
  - stack setup --no-terminal
  - stack build --ghc-options=-Werror --no-terminal
  - stack test --ghc-options=-Werror --no-terminal

cache:
  directories:
    - $HOME/.stack
